name: Test Automation & Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_marker:
        description: 'Choose which test suite marker to run'
        required: true
        default: 'regression'
        type: choice
        options:
        - regression
        - api
        - smoke

permissions:
  contents: write

env:
  CONSTANT_BASE_URL: "https://automationintesting.online"
  PYTHON_VERSION: "3.10"
  JAVA_VERSION: "17"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Install Poetry & Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry install --no-interaction --no-root
        poetry run playwright install

    - name: Create .env.local File
      run: |
        touch .env.local
        echo "BASE_URL=${{ env.CONSTANT_BASE_URL }}" >> .env.local

    - name: Execute Tests
      if: always()
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run pytest -m "${{ github.event.inputs.test_marker || 'regression' }}" --alluredir=allure-results

    - name: Get Allure History
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Ensure Deployment Directory Exists
      if: always()
      run: |
        mkdir -p allure-history
        if [ -z "$(ls -A allure-history)" ]; then
        echo "<h1>Initial Allure Report Generation Placeholder</h1>" > allure-history/index.html
        fi

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: allure-history

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history